// Prefabs: multi-tile props cut from the tilesets and drawn as y-sorted sprites.
// sheet: texture key; c, r: top-left tile; w, h: size in tiles.
// solid: collision rows counted from the bottom (default 1). door: tile column (from left) of the door, on the bottom row.
// examine: default object id used for inspection text; glow: offsets (px) of night lights.
export const SHEETS = {
  floor: { file: 'tiles/tilesetfloor.png', cols: 22 },
  water: { file: 'tiles/tilesetwater.png', cols: 28 },
  nature: { file: 'tiles/tilesetnature.png', cols: 24 },
  house: { file: 'tiles/tilesethouse.png', cols: 33 },
  element: { file: 'tiles/tilesetelement.png', cols: 16 },
  detail: { file: 'tiles/tilesetfloordetail.png', cols: 16 },
  towers: { file: 'tiles/tilesettowers.png', cols: 24 },
  camp: { file: 'tiles/tileset_camp.png', cols: 23 },
  field: { file: 'tiles/tilesetfield.png', cols: 5 },
  relief: { file: 'tiles/tilesetrelief.png', cols: 20 },
  wall: { file: 'tiles/interior_tilesetwallsimple.png', cols: 10 },
  ifloor: { file: 'tiles/interior_tilesetinteriorfloor.png', cols: 22 },
  bed: { file: 'tiles/tileset_bed.png', cols: 14 },
};

export const PREFABS = {
  // houses (3 tiles tall, door on bottom row)
  house_orange: { sheet: 'house', c: 0, r: 0, w: 4, h: 3, solid: 3, door: 1, glow: [[40, 38]] },
  house_beige: { sheet: 'house', c: 4, r: 0, w: 4, h: 3, solid: 3, door: 1, glow: [[40, 38]] },
  house_orange2: { sheet: 'house', c: 8, r: 0, w: 4, h: 3, solid: 3, door: 1, glow: [[40, 38]] },
  house_red: { sheet: 'house', c: 12, r: 0, w: 4, h: 3, solid: 3, door: 1, glow: [[40, 38]] },
  shop_blue: { sheet: 'house', c: 16, r: 0, w: 3, h: 3, solid: 3, door: 1, glow: [[10, 38], [38, 38]] },
  house_green: { sheet: 'house', c: 19, r: 0, w: 4, h: 3, solid: 3, door: 2, glow: [[18, 38]] },
  house_round: { sheet: 'house', c: 23, r: 0, w: 3, h: 3, solid: 3, door: 1, glow: [[8, 34], [40, 34]] },
  house_wood: { sheet: 'house', c: 26, r: 0, w: 3, h: 3, solid: 3, door: 1, glow: [[40, 38]] },
  inn: { sheet: 'house', c: 25, r: 14, w: 4, h: 5, solid: 3, door: 1, glow: [[36, 58], [50, 58]] },
  hut: { sheet: 'house', c: 29, r: 0, w: 4, h: 4, solid: 3, door: 1, glow: [[28, 50]] },
  field: { sheet: 'field', c: 0, r: 0, w: 3, h: 3, solid: 0, floor: true },
  scarecrow: { sheet: 'element', c: 15, r: 0, w: 1, h: 1, solid: 1 },
  sprout: { sheet: 'nature', c: 5, r: 11, w: 1, h: 1, solid: 0 },
  sign_fruit: { sheet: 'house', c: 20, r: 18, w: 1, h: 1, solid: 1 },
  torii: { sheet: 'house', c: 0, r: 5, w: 3, h: 2, solid: 0, blockCols: [0, 2] },
  // trees
  tree: { sheet: 'nature', c: 0, r: 0, w: 2, h: 2, solid: 1 },
  pine: { sheet: 'nature', c: 2, r: 0, w: 2, h: 2, solid: 1 },
  tree_bare: { sheet: 'nature', c: 4, r: 0, w: 2, h: 2, solid: 1 },
  tree_round: { sheet: 'nature', c: 6, r: 0, w: 2, h: 2, solid: 1 },
  tree_pink: { sheet: 'nature', c: 14, r: 0, w: 2, h: 2, solid: 1 },
  tree_lime: { sheet: 'nature', c: 16, r: 0, w: 2, h: 2, solid: 1 },
  tree_willow: { sheet: 'nature', c: 18, r: 0, w: 2, h: 2, solid: 1 },
  bigtree: { sheet: 'nature', c: 4, r: 2, w: 4, h: 3, solid: 1 },
  bigtree_pink: { sheet: 'nature', c: 12, r: 2, w: 4, h: 3, solid: 1 },
  bigtree_lime: { sheet: 'nature', c: 16, r: 2, w: 4, h: 3, solid: 1 },
  bigtree_yellow: { sheet: 'nature', c: 20, r: 2, w: 4, h: 3, solid: 1 },
  pines: { sheet: 'nature', c: 0, r: 2, w: 4, h: 3, solid: 1 },
  oak_pink: { sheet: 'nature', c: 0, r: 18, w: 3, h: 3, solid: 1 },
  oak: { sheet: 'nature', c: 3, r: 18, w: 3, h: 3, solid: 1 },
  oak_white: { sheet: 'nature', c: 6, r: 18, w: 3, h: 3, solid: 1 },
  oak_autumn: { sheet: 'nature', c: 9, r: 18, w: 3, h: 3, solid: 1 },
  stump: { sheet: 'nature', c: 0, r: 8, w: 2, h: 2, solid: 1 },
  log: { sheet: 'nature', c: 9, r: 8, w: 1, h: 1, solid: 1 },
  boulder: { sheet: 'nature', c: 15, r: 10, w: 2, h: 2, solid: 1 },
  boulder_big: { sheet: 'nature', c: 17, r: 10, w: 4, h: 3, solid: 2 },
  boulder_grey: { sheet: 'nature', c: 15, r: 14, w: 2, h: 2, solid: 1 },
  rock: { sheet: 'nature', c: 4, r: 13, w: 1, h: 1, solid: 1 },
  logs_upright: { sheet: 'nature', c: 12, r: 14, w: 2, h: 2, solid: 1 },
  bush: { sheet: 'nature', c: 2, r: 10, w: 1, h: 1, solid: 1 },
  bush_round: { sheet: 'nature', c: 6, r: 10, w: 1, h: 1, solid: 1 },
  berrybush: { sheet: 'nature', c: 7, r: 14, w: 2, h: 2, solid: 1 },
  berrybush_orange: { sheet: 'nature', c: 9, r: 14, w: 2, h: 2, solid: 1 },
  // small props (element sheet)
  barrel: { sheet: 'element', c: 1, r: 0, w: 1, h: 1, solid: 1 },
  pot: { sheet: 'element', c: 3, r: 0, w: 1, h: 1, solid: 1 },
  crate: { sheet: 'element', c: 6, r: 0, w: 1, h: 1, solid: 1 },
  crates: { sheet: 'element', c: 8, r: 0, w: 1, h: 1, solid: 1 },
  well: { sheet: 'element', c: 6, r: 1, w: 1, h: 1, solid: 1 },
  signpost: { sheet: 'element', c: 13, r: 0, w: 1, h: 1, solid: 1 },
  mailbox: { sheet: 'element', c: 3, r: 0, w: 1, h: 1, solid: 1 },
  lamp: { sheet: 'element', c: 6, r: 3, w: 1, h: 2, solid: 1, glow: [[8, 6]] },
  grave: { sheet: 'element', c: 4, r: 2, w: 1, h: 1, solid: 1 },
  cross: { sheet: 'element', c: 3, r: 2, w: 1, h: 1, solid: 1 },
  table_long: { sheet: 'element', c: 11, r: 1, w: 3, h: 1, solid: 1 },
  cart: { sheet: 'element', c: 0, r: 3, w: 2, h: 2, solid: 1 },
  // house sheet props
  fence_h: { sheet: 'house', c: 10, r: 5, w: 4, h: 1, solid: 1 },
  fence_post: { sheet: 'house', c: 10, r: 4, w: 1, h: 1, solid: 1 },
  market_goods: { sheet: 'house', c: 16, r: 13, w: 3, h: 1, solid: 1 },
  barrels: { sheet: 'house', c: 16, r: 15, w: 3, h: 1, solid: 1 },
  barrel_open: { sheet: 'house', c: 18, r: 12, w: 1, h: 1, solid: 1 },
  tent: { sheet: 'house', c: 16, r: 11, w: 2, h: 2, solid: 2 },
  counter: { sheet: 'house', c: 16, r: 16, w: 3, h: 1, solid: 1 },
  counter2: { sheet: 'house', c: 19, r: 16, w: 3, h: 1, solid: 1 },
  goods_crates: { sheet: 'house', c: 19, r: 14, w: 3, h: 1, solid: 1 },
  baskets: { sheet: 'house', c: 19, r: 15, w: 3, h: 1, solid: 1 },
  planks: { sheet: 'house', c: 31, r: 16, w: 2, h: 1, solid: 1 },
  planks_long: { sheet: 'house', c: 31, r: 19, w: 2, h: 1, solid: 1 },
  crates2: { sheet: 'house', c: 25, r: 19, w: 2, h: 1, solid: 1 },
  statue: { sheet: 'house', c: 1, r: 15, w: 2, h: 3, solid: 1 },
  statue_orb: { sheet: 'house', c: 3, r: 15, w: 2, h: 2, solid: 1, glow: [[16, 14]] },
  statue_monk: { sheet: 'house', c: 5, r: 15, w: 2, h: 2, solid: 1 },
  stone_lantern: { sheet: 'house', c: 7, r: 15, w: 1, h: 2, solid: 1, glow: [[8, 8]] },
  pillar: { sheet: 'house', c: 0, r: 15, w: 1, h: 3, solid: 1 },
  banner_red: { sheet: 'house', c: 23, r: 20, w: 1, h: 2, solid: 1 },
  banner_green: { sheet: 'house', c: 25, r: 20, w: 1, h: 2, solid: 1 },
  // interiors (element + bed sheets)
  i_bookcase: { sheet: 'element', c: 2, r: 7, w: 1, h: 2, solid: 1 },
  i_bookcase2: { sheet: 'element', c: 3, r: 7, w: 1, h: 2, solid: 1 },
  i_shelf: { sheet: 'element', c: 8, r: 7, w: 2, h: 2, solid: 1 },
  i_shelf2: { sheet: 'element', c: 10, r: 7, w: 2, h: 2, solid: 1 },
  i_dresser: { sheet: 'element', c: 6, r: 7, w: 2, h: 2, solid: 1 },
  i_drawers: { sheet: 'element', c: 1, r: 7, w: 1, h: 2, solid: 1 },
  i_plant: { sheet: 'element', c: 0, r: 7, w: 1, h: 2, solid: 1 },
  i_table: { sheet: 'element', c: 11, r: 1, w: 3, h: 1, solid: 1 },
  i_bench: { sheet: 'element', c: 2, r: 10, w: 3, h: 1, solid: 1 },
  i_stove: { sheet: 'element', c: 0, r: 10, w: 1, h: 1, solid: 1 },
  i_cauldron: { sheet: 'element', c: 4, r: 1, w: 1, h: 1, solid: 1 },
  i_chair: { sheet: 'element', c: 0, r: 9, w: 1, h: 1, solid: 1 },
  i_stool: { sheet: 'element', c: 3, r: 9, w: 1, h: 1, solid: 1 },
  i_clock: { sheet: 'element', c: 0, r: 5, w: 1, h: 2, solid: 1 },
  i_couch: { sheet: 'element', c: 4, r: 4, w: 2, h: 1, solid: 1 },
  i_jars: { sheet: 'element', c: 0, r: 1, w: 4, h: 1, solid: 1 },
  i_stairs: { sheet: 'element', c: 6, r: 11, w: 1, h: 1, solid: 1 },
  i_stairs_up: { sheet: 'element', c: 6, r: 12, w: 1, h: 2, solid: 2 },
  i_bed: { sheet: 'bed', c: 5, r: 0, w: 1, h: 2, solid: 2 },
  i_bed_red: { sheet: 'bed', c: 5, r: 3, w: 1, h: 2, solid: 2 },
  i_bed_blue: { sheet: 'bed', c: 12, r: 3, w: 1, h: 2, solid: 2 },
  i_bed_double: { sheet: 'bed', c: 0, r: 0, w: 2, h: 3, solid: 3 },
  i_rug: { sheet: 'bed', c: 2, r: 6, w: 3, h: 2, solid: 0, floor: true },
  i_rug_small: { sheet: 'bed', c: 0, r: 6, w: 2, h: 3, solid: 0, floor: true },
  // river road camp
  tent_camp: { sheet: 'camp', c: 4, r: 0, w: 3, h: 3, solid: 2, door: 1 },
  tent_camp2: { sheet: 'camp', c: 7, r: 0, w: 3, h: 3, solid: 2 },
  tent_ruined: { sheet: 'camp', c: 10, r: 0, w: 3, h: 3, solid: 2 },
  firepit: { sheet: 'camp', c: 12, r: 3, w: 2, h: 2, solid: 2, glow: [[16, 12]] },
  camp_pot: { sheet: 'camp', c: 8, r: 3, w: 2, h: 2, solid: 1 },
  weapon_rack: { sheet: 'camp', c: 6, r: 5, w: 1, h: 2, solid: 1 },
  camp_table: { sheet: 'camp', c: 1, r: 5, w: 2, h: 2, solid: 1 },
  log_bench: { sheet: 'camp', c: 0, r: 7, w: 3, h: 1, solid: 1 },
  chest: { sheet: 'camp', c: 4, r: 8, w: 1, h: 1, solid: 1 },
  big_barrel: { sheet: 'camp', c: 4, r: 6, w: 2, h: 2, solid: 1 },
};
