// Fallback lines when inspecting something with no special text. Keys match prefab name prefixes.
export const FALLBACK = {
  house: ['A cosy house. Someone is humming inside.', 'The door is shut. A smell of soup escapes anyway.', 'Warm light leaks under the door.'],
  hut: ['A little cabin. Smoke curls from the chimney like a question.', 'Someone inside is arguing with a kettle.'],
  inn: ['The inn. Laughter and the smell of plum cake leak through the walls.'],
  field: ['Tidy rows of turnips. Fen swears one of them is named after you.', 'The soil is warm. Something is growing, slowly, stubbornly.'],
  scarecrow: ['The scarecrow wears Hobb\'s old hat. The crows find this hilarious.'],
  sprout: ['A tiny sprout. It will be a turnip someday. Dream big.'],
  sign: ['A painted sign: a strawberry. Coral insists it is a plum.'],
  crates: ['Crates of lantern glass, packed in straw.'],
  shop: ['A little shop. The sign is freshly painted.', 'Closed for the evening. Mostly.'],
  bigtree: ['An old tree. Its roots have seen more storms than you.', 'Birds argue somewhere in the leaves.'],
  tree: ['A tree. It rustles, politely.', 'Bark carved with initials: "S + ?". Hm.', 'A beetle waves at you. Probably.'],
  pine: ['Pine needles and resin. It smells like winter.', 'Tall and patient.'],
  oak: ['A grand oak. It could shelter half the village.', 'Acorns everywhere. Squirrels are winning.'],
  stump: ['A stump, smooth enough to sit on.', 'Hobb was here. Clearly.'],
  log: ['A cut log, waiting to become something.'],
  logs: ['Stacked timber. Neat, like a promise kept.'],
  boulder: ['A mossy boulder. It does not budge.', 'Something is scratched on it: a tiny lantern.'],
  rock: ['Just a rock. A good rock, though.'],
  bush: ['A bush. It rustles back at you.', 'Nothing hiding in there. Just leaves.'],
  berrybush: ['Berries! Too sour to eat. Great for pies.', 'The berries glow faintly at dusk.'],
  barrel: ['A barrel of rainwater.', 'Smells of pickled plums.'],
  pot: ['A clay pot, painted with little waves.'],
  crate: ['Crates of lantern glass, packed in straw.'],
  well: ['The well is deep. Your lantern light goes down, down.'],
  signpost: ['The sign points everywhere at once. Very Puddlewick.'],
  mailbox: ['A mailbox. Not yours to open.'],
  lamp: ['A lamp post. Its wick flickers, weaker than it should.'],
  grave: ['An old marker. The name has worn away.'],
  cross: ['Two sticks tied together. Someone remembered.'],
  table: ['A long bench. Warm from the day.'],
  cart: ['A broken cart. One wheel is missing. So is the cart owner.'],
  fence: ['A little fence. It keeps the garden in, mostly.'],
  market: ['Fish, cabbages, apples. The fish looks surprised.'],
  tent: ['A patched market tent. It flaps gently.'],
  counter: ['A wooden counter, polished by elbows.'],
  goods: ['Crates of goods for the market.'],
  baskets: ['Baskets of dried herbs.'],
  planks: ['Lumber, stacked high. Not for you. Yet.'],
  statue: ['A stone guardian. Its eyes follow you. Rude.'],
  stone_lantern: ['A stone lantern. Cold tonight.'],
  pillar: ['A worn pillar from older days.'],
  banner: ['A festival banner, faded by salt wind.'],
  torii: ['A red gate. Walking through it feels like a small promise.'],
  water: ['Cool water. Tiny fish scatter from your shadow.', 'The water smells of salt and river weed.', 'Your reflection waves back. It has your lantern.'],
  flower: ['Flowers. They lean toward your lantern.', 'You smell the flowers. Nice.', 'A bee is asleep inside this one.'],
  wisp: ['The wisp hums a note only you can hear.', 'It bumps your cheek. Warm.'],
  cat: ['The cat ignores you. Magnificently.', 'Purrs, once, then pretends it did not.'],
  dog: ['The dog wags so hard its whole body wags.', 'It brings you a stick. The stick is wet.'],
  frog: ['Ribbit. You feel judged.', 'The frog has seen things. Pond things.'],
  tent: ['A Wickwarden tent. It smells of lamp oil and rules.'],
  firepit: ['The camp fire burns violet at the edges. That is not normal.'],
  weapon: ['Spears, shields, and one very polished lantern hook.'],
  camp: ['Camp gear, stamped with a violet seal.'],
  log_bench: ['A log bench, worn smooth by bored guards.'],
  big_barrel: ['A barrel labeled SURPLUS LIGHT. It is empty. For now.'],
  chest: ['Locked. The lock is shaped like a moth.'],
  i_: ['Homey. Someone keeps this place with love.', 'Everything smells faintly of plum cake.'],
  thing: ['Nothing unusual. Or is there?', 'You look closer. Still nothing. Still curious.'],
};
